# Generated by Django 4.0.1 on 2022-12-09 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('body', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
