# Generated by Django 4.0.1 on 2022-12-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='id',
            field=models.CharField(max_length=2, primary_key=True, serialize=False),
        ),
    ]
