# Generated by Django 4.0.1 on 2023-01-03 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_mlmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('body', models.CharField(max_length=50)),
            ],
        ),
    ]
