# Generated by Django 4.1.5 on 2023-02-21 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Accounts',
        ),
    ]
